src/Entity/Projet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjetRepository")
 */
class Projet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $nom;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="projets")
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Equipe", inversedBy="YES")
     * @ORM\JoinColumn(nullable=false)
     */
    private $equipe;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tache", mappedBy="projet")
     */
   private $taches ;

   public function __construct()
   {
       $this->taches = new ArrayCollection();
   }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getEquipe(): ?equipe
    {
        return $this->equipe;
    }

    public function setEquipe(?equipe $equipe): self
    {
        $this->equipe = $equipe;

        return $this;
    }

    /**
     * @return Collection|Tache[]
     */
    public function getTaches(): Collection
    {
        return $this->taches;
    }

    public function addTach(Tache $tach): self
    {
        if (!$this->taches->contains($tach)) {
            $this->taches[] = $tach;
            $tach->setProjet($this);
        }

        return $this;
    }

    public function removeTach(Tache $tach): self
    {
        if ($this->taches->contains($tach)) {
            $this->taches->removeElement($tach);
            // set the owning side to null (unless already changed)
            if ($tach->getProjet() === $this) {
                $tach->setProjet(null);
            }
        }

        return $this;
    }

   
}

src/Form/ProjetType.php
<?php

namespace App\Form;

use App\Entity\Projet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_debut')
            ->add('date_fin')
            ->add('description')
            ->add('nom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Projet::class,
        ]);
    }
}

src/Controller/ProjetController.php
<?php
namespace App\Controller;

use App\Entity\Projet;
use App\Entity\Categorie;
use App\Form\ProjetType;
use App\Repository\ProjetRepository;
use App\Repository\CategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Search;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

/**
 * @Route("/projet")
 */
class ProjetController extends AbstractController
{
    /**
     * @Route("/", name="projet_index", methods={"GET","POST"})
     */
    
    public function index(ProjetRepository $projetRepository, Request $rq): Response

    {   
        $nb= $this->getDoctrine()->getManager()
        ->createQuery('SELECT COUNT(c.id) FROM App\Entity\Categorie c')
        ->getSingleScalarResult();

        $search= new Search;
         $form = $this->createFormBuilder($search)
            ->setAction($this->generateUrl('projet_index'))
            ->setMethod('GET')
            ->add('data', TextType::class)
            ->add('filtre', ChoiceType::class, [
                        'choices' => [
                            'nom' => true,
                            'date_debut' => false,
                            'date_fin' => false,

                        ]])
            ->add('search', SubmitType::class, ['label' => 'OK'])

            ->getForm();
            $form->handleRequest($rq);
            $data= $form->get("data")->getData();
            $filtre= $form->get("filtre")->getData();

        if ($form->isSubmitted() && $form->isValid()) {
           if($filtre=='nom')
                $projets = $projetRepository->findByNom($data);
            else if ($form->filte=='date_debut')
                $projets = $projetRepository->findByDateDebut($data);
            else
                $projets = $projetRepository->findByDateFin($data);}
            
        else 
            $projets = $projetRepository->findAll();

        return $this->render('projet/index.html.twig', [
            
            'projets' => $projets,
            'categorie_cnt'=> $nb,
            "form"=>$form->createView(),


                    # code...
                
                # code...
            
        ]);
    }

    /**
     * @Route("/new", name="projet_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $projet = new Projet();
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($projet);
            $entityManager->flush();

            return $this->redirectToRoute('projet_index');
        }

        return $this->render('projet/new.html.twig', [
            'projet' => $projet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="projet_show", methods={"GET"})
     */
    public function show(Projet $projet): Response
    {
        return $this->render('projet/show.html.twig', [
            'projet' => $projet,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="projet_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Projet $projet): Response
    {
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('projet_index');
        }

        return $this->render('projet/edit.html.twig', [
            'projet' => $projet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="projet_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Projet $projet): Response
    {
        if ($this->isCsrfTokenValid('delete'.$projet->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($projet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('projet_index');
    }
}

templates/projet/_delete_form.html.twig
<form method="post" action="{{ path('projet_delete', {'id': projet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ projet.id) }}">
    <button class="btn">Delete</button>
</form>

templates/projet/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Projet{% endblock %}

{% block body %}
    <h1>Edit Projet</h1>

    {{ include('projet/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('projet_index') }}">back to list</a>

    {{ include('projet/_delete_form.html.twig') }}
{% endblock %}

templates/projet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projet index{% endblock %}
{% block body %}
{{ include('search/_search.html.twig') }}
{% for i in categorie_cnt %}
<div class='col-{{12/categorie_cnt}}'>
 {%for projet in projets%}
{%if (projet.Categorie.id==i)%}
 {{projet.nom}}
{%endif%}
{%endfor%}

</div>
{%endfor%}
    <h1> liste des projets : {{categorie_cnt}}</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>categorie</th>
               <th>actions</th>
            </tr>
        </thead>
        <tbody>
                 {% for projet in projets  %}

            <tr>
                
                <td>{{ projet.nom }}</td>
               <td>{{projet.categorie.nom}}</td>
                <td>                   
                    <a href="{{ path('projet_show', {'id': projet.id}) }}">show</a>
                    <a href="{{ path('projet_edit', {'id': projet.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
    
        </tbody>
    </table>
    <a href="{{ path('projet_new') }}">Create new</a>
{% endblock %}

templates/projet/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Projet{% endblock %}

{% block body %}
    <h1>Create new Projet</h1>

    {{ include('projet/_form.html.twig') }}

    <a href="{{ path('projet_index') }}">back to list</a>
{% endblock %}

templates/projet/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projet{% endblock %}

{% block body %}
    <h1>Projet</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ projet.id }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ projet.dateDebut ? projet.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ projet.dateFin ? projet.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ projet.description }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ projet.nom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('projet_index') }}">back to list</a>

    <a href="{{ path('projet_edit', {'id': projet.id}) }}">edit</a>

    {{ include('projet/_delete_form.html.twig') }}
{% endblock %}