src/Entity/Commantaire.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommantaireRepository")
 */
class Commantaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_comm;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\tache")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tache;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $utlisateur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateComm(): ?\DateTimeInterface
    {
        return $this->date_comm;
    }

    public function setDateComm(\DateTimeInterface $date_comm): self
    {
        $this->date_comm = $date_comm;

        return $this;
    }

    public function getTache(): ?tache
    {
        return $this->tache;
    }

    public function setTache(?tache $tache): self
    {
        $this->tache = $tache;

        return $this;
    }

    public function getUtlisateur(): ?string
    {
        return $this->utlisateur;
    }

    public function setUtlisateur(string $utlisateur): self
    {
        $this->utlisateur = $utlisateur;

        return $this;
    }
}

src/Form/CommantaireType.php
<?php

namespace App\Form;

use App\Entity\Commantaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommantaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_comm')
            ->add('utlisateur')
            ->add('tache')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commantaire::class,
        ]);
    }
}

src/Controller/CommantaireController.php
<?php

namespace App\Controller;

use App\Entity\Commantaire;
use App\Form\CommantaireType;
use App\Repository\CommantaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/commantaire")
 */
class CommantaireController extends AbstractController
{
    /**
     * @Route("/", name="commantaire_index", methods={"GET"})
     */
    public function index(CommantaireRepository $commantaireRepository): Response
    {
        return $this->render('commantaire/index.html.twig', [
            'commantaires' => $commantaireRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="commantaire_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $commantaire = new Commantaire();
        $form = $this->createForm(CommantaireType::class, $commantaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commantaire);
            $entityManager->flush();

            return $this->redirectToRoute('commantaire_index');
        }

        return $this->render('commantaire/new.html.twig', [
            'commantaire' => $commantaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commantaire_show", methods={"GET"})
     */
    public function show(Commantaire $commantaire): Response
    {
        return $this->render('commantaire/show.html.twig', [
            'commantaire' => $commantaire,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="commantaire_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Commantaire $commantaire): Response
    {
        $form = $this->createForm(CommantaireType::class, $commantaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('commantaire_index');
        }

        return $this->render('commantaire/edit.html.twig', [
            'commantaire' => $commantaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commantaire_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Commantaire $commantaire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commantaire->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($commantaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('commantaire_index');
    }
}

templates/commantaire/_delete_form.html.twig
<form method="post" action="{{ path('commantaire_delete', {'id': commantaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commantaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commantaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commantaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commantaire{% endblock %}

{% block body %}
    <h1>Edit Commantaire</h1>

    {{ include('commantaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commantaire_index') }}">back to list</a>

    {{ include('commantaire/_delete_form.html.twig') }}
{% endblock %}

templates/commantaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commantaire index{% endblock %}

{% block body %}
    <h1>Commantaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_comm</th>
                <th>Utlisateur</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commantaire in commantaires %}
            <tr>
                <td>{{ commantaire.id }}</td>
                <td>{{ commantaire.dateComm ? commantaire.dateComm|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commantaire.utlisateur }}</td>
                <td>
                    <a href="{{ path('commantaire_show', {'id': commantaire.id}) }}">show</a>
                    <a href="{{ path('commantaire_edit', {'id': commantaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('commantaire_new') }}">Create new</a>
{% endblock %}

templates/commantaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commantaire{% endblock %}

{% block body %}
    <h1>Create new Commantaire</h1>

    {{ include('commantaire/_form.html.twig') }}

    <a href="{{ path('commantaire_index') }}">back to list</a>
{% endblock %}

templates/commantaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commantaire{% endblock %}

{% block body %}
    <h1>Commantaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commantaire.id }}</td>
            </tr>
            <tr>
                <th>Date_comm</th>
                <td>{{ commantaire.dateComm ? commantaire.dateComm|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Utlisateur</th>
                <td>{{ commantaire.utlisateur }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('commantaire_index') }}">back to list</a>

    <a href="{{ path('commantaire_edit', {'id': commantaire.id}) }}">edit</a>

    {{ include('commantaire/_delete_form.html.twig') }}
{% endblock %}